spring:
  application:
    name: api-geteway
server:
  port: 8089

zuul:
  prefix: /api
  routes:
    api-a:
      path: /student-service/**
      serviceId: student-service
      # url: http://localhost:8083
      # 转发前是否跳过前缀,默认为true， prefix: /api
      stripPrefix: true
      # 是否开启重试，具体重试设置是在Ribbon的配置中设置
      retryable: true
    api-b:
      path: /feign-consumer/**
      serviceId: feign-consumer
      # url: http://localhost:8088
      # 转发前是否跳过前缀,默认为true， prefix: /api
      stripPrefix: true
      # 是否开启重试，具体重试设置是在Ribbon的配置中设置
      retryable: true
ribbon:
  eureka:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/
